import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/global.css";
import { ThemeProvider } from "@/components/theme-provider";
import StoreProvider from "@/components/store-provider";
import Sidebar from "@/components/sidebar/Sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Hirenixs",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <link rel="icon" href="/favicons/favicon.ico" />
            <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
            <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
            <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
            <link rel="manifest" href="/site.webmanifest" />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <StoreProvider>
                    <ThemeProvider>
                        <Toaster richColors position="top-right" duration={5000} />
                        <div className="">
                            <Sidebar />
                            <main className="">{children}</main>
                        </div>
                    </ThemeProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
